-- First remove existing job types
TRUNCATE TABLE job_types CASCADE;

-- Insert comprehensive list of job types
INSERT INTO job_types (name, code, description) VALUES
  ('Administrative', 'ADMIN', 'Administrative tasks and paperwork'),
  ('Buildout', 'BUILD', 'Building and construction work'),
  ('Cleaning', 'CLEAN', 'System and component cleaning'),
  ('Construction', 'CONST', 'New construction installation'),
  ('Consultation', 'CONSULT', 'Customer consultation and assessment'),
  ('Delivery', 'DELIV', 'Equipment and parts delivery'),
  ('Design', 'DESIGN', 'System design and planning'),
  ('Emergency Service Call', 'EMERG', 'Emergency repair services'),
  ('Exchange', 'EXCH', 'Equipment exchange or swap'),
  ('Hookup', 'HOOK', 'System connection and hookup'),
  ('Inspection', 'INSP', 'System inspection and assessment'),
  ('Inspection Repair', 'INSPR', 'Repairs identified during inspection'),
  ('Installation', 'INST', 'New equipment installation'),
  ('Pickup', 'PICK', 'Equipment or parts pickup'),
  ('Planned Maintenance', 'PLANM', 'Scheduled maintenance work'),
  ('Preventative Maintenance', 'PM', 'Regular preventative maintenance'),
  ('Priority Inspection', 'PRINS', 'Urgent inspection needs'),
  ('Priority Service Call', 'PRSVC', 'High-priority service requests'),
  ('Quality Assurance', 'QA', 'Quality checks and verification'),
  ('Reinspection', 'REINS', 'Follow-up inspection'),
  ('Repair', 'REP', 'Equipment repairs'),
  ('Replacement', 'REPL', 'Equipment replacement'),
  ('Retrofit', 'RETRO', 'System retrofitting and upgrades'),
  ('Sales', 'SALES', 'Equipment and service sales'),
  ('Service Call', 'SVC', 'General service calls'),
  ('Start Up', 'START', 'New system startup and testing'),
  ('Survey', 'SURV', 'Site and system surveys'),
  ('Testing', 'TEST', 'System testing and diagnostics'),
  ('Training', 'TRAIN', 'Customer or staff training'),
  ('Unknown', 'UNK', 'Unclassified job type'),
  ('Upgrade', 'UPG', 'System upgrades'),
  ('Urgent Service Call', 'URG', 'Time-sensitive service needs'),
  ('Warranty Call', 'WAR', 'Warranty-related service');